version: '3'
services:
  backend:
    build:
      context: ./backend  # Path to your Django backend Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend  # Path to your React frontend Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start
