# Generated by Django 4.2.5 on 2023-10-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0002_dayoff_end_date_dayoff_off_type_dayoff_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='why',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
