# Generated by Django 4.2.5 on 2023-10-28 07:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0005_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='team',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=300, null=True),
        ),
    ]
