# Generated by Django 4.2.5 on 2023-10-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0007_remove_users_team_users_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='editable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
